spring:
  application:
    name: gateway-server

server:
  port: 8765

zuul:
  prefix: /api
  routes:
    user:
      path: /user/**
      serviceId: user-service
    course:
      path: /course/**
      serviceId: course-service
    log:
      path: /log/**
      serviceId: log-service
    ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin
    sensitiveHeaders: Cookie,Set-Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
